name: PR:3.4

on:
  pull_request:
    branches:
      - 3.4

jobs:
  Ubuntu20.04-ARM64:
    uses: opencv/ci-gha-workflow/.github/workflows/OCV-PR-3.4-ARM64.yaml@main

  Ubuntu20.04-x64:
    uses: opencv/ci-gha-workflow/.github/workflows/OCV-PR-3.4-U20.yaml@main

  Windows10-x64:
    uses: opencv/ci-gha-workflow/.github/workflows/OCV-PR-3.4-W10.yaml@main

  macOS-ARM64:
    uses: opencv/ci-gha-workflow/.github/workflows/OCV-PR-3.4-macOS-ARM64.yaml@main

  macOS-x64:
    uses: opencv/ci-gha-workflow/.github/workflows/OCV-PR-3.4-macOS-x86_64.yaml@main

  iOS:
    uses: opencv/ci-gha-workflow/.github/workflows/OCV-PR-3.4-iOS.yaml@main
