name: PR:4.x

on:
  pull_request:
    branches:
      - 4.x

jobs:
  ARM64:
    uses: opencv/ci-gha-workflow/.github/workflows/OCV-PR-4.x-ARM64.yaml@main

  U20:
    uses: opencv/ci-gha-workflow/.github/workflows/OCV-PR-4.x-U20.yaml@main

  W10:
    uses: opencv/ci-gha-workflow/.github/workflows/OCV-PR-4.x-W10.yaml@main

  TIM-VX:
    uses: opencv/ci-gha-workflow/.github/workflows/OCV-timvx-backend-tests-4.x.yml@main